Core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home, name='home'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search_results/', views.SearchResultsView.as_view(),
         name='search_results'),
]

GestaoDePraticasDiarias_v6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Core.urls')),
    path('', include('Users.urls')),
    path('', include('Activities.urls')),
    path('', include('processes.urls')),
]

Users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "Users"

urlpatterns = [
    path("utilizadores", views.utilizadores, name="utilizadores"),
    path("utilizadores/UserCreate", login_required(views.UserCreate.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserCreate"),
    path("utilizadores/UserDelete/<int:pk>", login_required(views.UserDelete.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserDelete"),
    path("utilizadores/UserUpdate/<int:pk>", login_required(views.UserUpdate.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserUpdate"),
    path("utilizadores/UserUpdateEmail/<int:pk>", login_required(views.UserUpdateEmail.as_view(success_url=('/')),login_url="/login"),  name="UserUpdateEmail"),
    path("utilizadores/UserChangePassword/<int:pk>", login_required(views.UserChangePassword.as_view(success_url=('/')),login_url="/login"),  name="UserUpdatePassword"),
    path("utilizadores/UserDetail/<int:pk>", login_required(views.UserDetail.as_view(),login_url="/login"), name="UserDetail"  ),
    path("empresas", views.empresas, name="empresas"),
    path("empresas/OrganizationCreate", login_required(views.OrganizationCreate.as_view(success_url=('/empresas')), login_url="/login"), name="empresas"),
    path("empresas/OrganizationDelete/<int:pk>", login_required(views.OrganizationDelete.as_view(success_url=('/empresas')),login_url="/login"),  name="OrganizationDelete"),
    path("empresas/OrganizationUpdate/<int:pk>", login_required(views.OrganizationUpdate.as_view(success_url=('/empresas')),login_url="/login"),  name="OrganizationUpdate"),
    path("empresas/OrganizationDetail/<int:pk>", login_required(views.OrganizationDetail.as_view(),login_url="/login"), name="OrganizationDetail"  ),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
]

Activities/models.py
from django.db import models

# Create your models here.


class Tags(models.Model):
    name = models.IntegerField(db_column='Name', blank=True, null=True)
    id = models.AutoField(db_column='ID', primary_key=True)

    class Meta:
        managed = True
        db_table = 'Tags'


class Pattern(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID')
    patternname = models.CharField(db_column='PatternName', max_length=255, verbose_name='Padrão')
    description = models.TextField(db_column='Description')
    data_creation = models.DateField(db_column='Data Creation', null=True)
    groups = models.ManyToManyField('Group')

    class Meta:
        managed = True
        db_table = 'Pattern'
    def __str__(self):
        return self.patternname
    def list_groups(self):
        return ", ".join([groups.groupname for groups in self.groups.all()])


class Group(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, null=True, db_column='UserID')
    groupname = models.CharField(db_column='GroupName', unique=True, max_length=255, verbose_name='Agrupamento')
    creationdate = models.DateField(db_column='CreationDate', blank=True, null=True)
    name = models.CharField(db_column='Name', max_length=255)
    description = models.TextField(db_column='Description')
    sentences = models.ManyToManyField('Sentence')

    class Meta:
        managed = True
        db_table = 'Group'
    def __str__(self):
        return self.groupname
    def list_sentences(self):
        return ", ".join([sentences.sentencename for sentences in self.sentences.all()])


class Sentence(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID')
    sentencename = models.CharField(db_column='SentenceName', max_length=255, verbose_name="Frase")
    datecreated = models.DateField(db_column='DateCreated', null=True)
    subject = models.CharField(db_column='Subject', max_length=255, verbose_name="Sujeito")
    receiver = models.CharField(db_column='Receiver', max_length=255, blank=True, null=False, verbose_name="Recetor")
    datarealizado = models.DateField(db_column='DataRealizado',blank=True, null=True)
    verbid = models.ForeignKey('Verb', models.DO_NOTHING, db_column='VerbID', verbose_name="Verbo", blank=True, null=True)
    resourceid = models.ForeignKey('Resource', models.SET_NULL, db_column='ResourceID', verbose_name="Recurso", null=True, blank=True)
    artefactid = models.ForeignKey('Artefact', models.SET_NULL, db_column='ArtefactID', verbose_name="Artefacto", null=True, blank=True)

    verb_sug = models.CharField(db_column='VerbSug', max_length=255, verbose_name="Verbo Sugerido", blank=True)

    resource_sug = models.CharField(db_column='ResourceSug', max_length=255, verbose_name="Recurso Sugerido", blank=True)

    art_sug = models.CharField(db_column='ArtefactSug', max_length=255, verbose_name="Artefacto Sugerido", blank=True)

    class Meta:
        managed = True
        db_table = 'Sentence'
    def __str__(self):
        return self.sentencename


class Verb(models.Model):
    verb_type_choices = (('Produtivo','Produtivo'), ('Comunicativo','Comunicativo'))
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID', blank=True, null=True)
    datecreated = models.DateField(db_column='DateCreated', blank=True, null=True)
    verbname = models.CharField(db_column='VerbName', unique=True, max_length=255, verbose_name='Verbo')
    verbtype = models.CharField(db_column='VerbType', max_length=255, choices=verb_type_choices, verbose_name='Tipo')

    class Meta:
        managed = True
        db_table = 'Verb'
    def __str__(self):
        return self.verbname
        
        
        
class Resource(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID', blank=True, null=True)
    resourcename = models.CharField(db_column='ResourceName', unique=True, max_length=255, verbose_name='Recurso')
    datecreated = models.DateField(db_column='DateCreated')

    class Meta:
        managed = True
        db_table = 'Resource'
    def __str__(self):
        return self.resourcename
 
 
class Artefact(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID', blank=True, null=True)
    artefactname = models.CharField(db_column='ArtefactName', unique=True, max_length=255, verbose_name='Artefacto')
    datecreated = models.DateField(db_column='DateCreated')

    class Meta:
        managed = True
        db_table = 'Artefacto'
    def __str__(self):
        return self.artefactname
       

Users/models.py
import django
from django.db import models
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import AbstractUser, Group

# Create your models here.
class Organization(models.Model):
    name = models.CharField(max_length=200, unique=True, blank=False)
    location = models.CharField(max_length=200, blank=False)
    def __str__(self):
        return self.name



class User(AbstractUser):
    id = models.AutoField(db_column='ID',primary_key=True)
    username = models.CharField(db_column='UserName',
                                max_length=255,
                                unique=True)
    useremail = models.CharField(db_column='UserEmail',
                                 max_length=255)
    password = models.CharField(db_column='Password',
                                max_length=255,
                                blank=True, null=True)

    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)




    class Meta:
        managed = True
        db_table = 'User'
        permissions = (
            ("test_GProc", "Teste de permissao geral Gestor de Processos"),
            ("test_Analist", "Teste de permissao geral Analista"),
            ("test_Func", "Teste de permissao geral Funcionário"),
            ("test_Admin", "Teste de permissao geral Administrador"),)

processes/models.py
import django
from django.db import models
from django.core import validators
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import AbstractUser, Group
from Users.models import User, Organization
from Activities.models import Pattern
from django.core.exceptions import ValidationError

# Create your models here.

class Process(models.Model):
    process_name = models.CharField(max_length=200)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    creation_date = models.DateTimeField("date created", default=django.utils.timezone.now)
    description = models.TextField(max_length=400)
    


    def __str__(self):
        return self.process_name

class Activity(models.Model):
    activity_name = models.CharField(max_length=200)
    process = models.ForeignKey(Process, null=True,blank=True, on_delete=models.SET_NULL)
    description = models.TextField(max_length=400)
    role = models.ManyToManyField('Role', blank=True)
    original = models.ForeignKey('self', blank=True, null=True,on_delete=models.SET_NULL)
    pattern = models.ManyToManyField('Activities.Pattern', blank=True)
    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)
    class Meta:
        verbose_name = ("Activity") 

    def __str__(self):
        return self.activity_name

    def clean(self):
        incident = Activity.objects.filter(activity_name=self.activity_name).exclude(process__isnull=False)
        if incident and self.original is None:
                if not Activity.objects.filter(id=self.pk).exists() : # check if any object exists
                    raise ValidationError('Já existe uma Actividade Base com este nome.')
                elif not incident[0].pk == self.pk: 
                    raise ValidationError('Já existe uma Actividade Base com este nome.')

class Role(models.Model):
    role_name = models.CharField(max_length=200)
    description = models.TextField(max_length=300)
    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.role_name



class Product(models.Model):
    product_name = models.CharField(max_length=200)
    product_format = models.CharField(max_length=200)
    activity = models.ManyToManyField(Activity, blank=True)
    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)
    product_input = models.CharField(max_length=200)
    product_output = models.CharField(max_length=200)
    def clean(self):
        incident = Product.objects.filter(organization__id=self.organization.id).filter(product_name=self.product_name)
        if incident:
            if not Product.objects.filter(id=self.pk).exists() : # check if any object exists
                raise ValidationError('Já existe um Produto com este nome.')
            elif not incident[0].pk == self.pk: 
                raise ValidationError('Já existe um Produto com este nome.')

    def __str__(self):
        return self.product_name

templates/main/header.html
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registo diário</title>
    <link rel="stylesheet" href="{% static 'css/googleapis.css' %}">
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jQuery.js' %}" ></script>
    <!-- Font Awesome JS -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <link rel='icon' href='favicon.ico' type='image/x-icon' sizes="16x16" />
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>   
</head>
{% block navbar %}
{% endblock %}

templates/main/home.html
{% extends "main/navbar.html" %}
{% block title %}
Página Inicial
{% endblock %}
 {% block content %}
	<div class="container">

        <!--{% if perms.Users.add_user %}
            {% include "tables/user.html" with object_list=users %}
        {% endif %}-->
        {% if perms.Activities.add_sentence %}
            {% include "tables/sentence.html" with object_list=sentences %}
        {% endif %}
        {% if perms.Activities.add_group %}
            {% include "tables/group.html" with object_list=groups %}
        {% endif %}
        {% if perms.Activities.add_pattern %}
            {% include "tables/pattern.html" with object_list=patterns %}
        {% endif %}
        {% if perms.Users.test_GProc or  perms.Users.test_Analist %}
        {% include "processes/includes/gp_main_area.html" %}
        {% elif perms.Users.test_Admin %}
        {% include "processes/includes/admin_main_area.html" %}
        {% endif %}
        <!--{% if perms.Processes.add_process %}
            {% include "tables/process.html" with object_list=processes %}
        {% endif %}
        {% if perms.Processes.add_activity %}
            {% include "tables/activity.html" with object_list=activities %}
        {% endif %}-->
	</div>
{% endblock %}

templates/main/modal.html
<div class="modal fade" data-backdrop="static" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <form id="f" class="ajax" method="post">
                <div class="modal-body" id="modal-body">
                </div>
                <div class="modal-footer">
                    <a class="text-danger mr-3" href="" data-dismiss="modal">Cancelar</a>
                    <button type="submit" class="btn text-white">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" data-backdrop="static" id="deleteModalVerb" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <form id="delverb" class="ajax" method="post">
                <div class="modal-body">
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" data-backdrop="static" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <form id="del" class="ajax" method="post">
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <a class="text-danger mr-3" href="" data-dismiss="modal">Cancelar</a>
                    <button type="submit" class="btn text-white">Eliminar</button>   
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" data-backdrop="static" id="Searchmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <form class="ajax" method="get" action="{% url 'search_results' %}">
                <div class="modal-body" id="modal-body">
                </div>
                <div class="modal-footer">
                    <a class="text-danger mr-3" href="" data-dismiss="modal">Cancelar</a>
                    <button type="submit" class="btn text-white">Pesquisar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" data-backdrop="static" id="Viewmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title"></h2>
                <a class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </a>
            </div>
            <form id="f" class="ajax" method="post">
                <div class="modal-body" id="modal-body">
                </div>
                <div class="modal-footer">
                </div>
            </form>
        </div>
    </div>
</div>

templates/main/navbar.html
{% extends "main/header.html" %}
{% block navbar %}
<body>  
<div class="wrapper">
    <nav id="sidebar" class="navbar-info" style="background:#058096;">
        <div class="sidebar-header" style="background:#058096;">
            <h4 class="text-white">REGISTO DIÁRIO </h4>
        </div>
        <ul class="list-unstyled components text-white">
            <li {% if request.path == "/" %} class="active" {% endif %}>
                <a href='{% url "home" %}' style="margin-top:10px;"><i class="material-icons">home</i> PÁGINA INICIAL</a>
            </li>
        </ul>
        <ul class="list-unstyled components text-white">
                {% include "main/sidebar/frase.html" %}
                {% include "main/sidebar/agrupamento.html" %}
                {% include "main/sidebar/padrao.html" %}
				{% include "main/sidebar/processo.html" %}
				{% include "main/sidebar/utilizador.html" %}
        </ul>
	</nav>
	<div id="content">
		<nav class="navbar navbar-expand-lg navbar-light">
			<button type="button" id="sidebarCollapse" class="btn text-white" style="background:#058096;"><!--btm-info-->
				<i class="fas fa-align-left"></i>
			</button>
			<div class="navegation">
			<h1 class="titulo-principal mt-2"> {% block title %} {{ page.title }} {% endblock %}</h1>
			</div>
		<span style="position:absolute; left:10vw;width:50vw; max-width:50vw!important">	{% include "processes/includes/messages.html" %}</span>
			<button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
				<ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <button type="button" href="#" class="btn float-right text-white" data-toggle="modal" onclick='newModal("{% url "search" %}", "Pesquisa Avançada", "#Searchmodal", "modal-lg")'>Pesquisa Avançada <i class="fa fa-search"></i></button>
                    </li>
					<li class="nav-item">
						<div class="btn-group">
							<button type="button" class="btn btn-warning text-left dropdown-toggle" style="width:100px;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">+ Novo </button>
							<div class="dropdown-menu dropdown-menu-right">
								{% include "main/topbar/utilizador.html" %}
								{% include "main/topbar/frase.html" %}
								{% include "main/topbar/verbo.html" %}
                                {% include "main/topbar/recurso.html" %}
                                {% include "main/topbar/artefacto.html" %}
								{% include "main/topbar/agrupamento.html" %}
								{% include "main/topbar/padrao.html" %}
								{% include "main/topbar/processo.html" %}
								{% include "main/topbar/atividade.html" %}
                                {% include "main/topbar/papel.html" %}
								{% include "main/topbar/produto.html" %}
								
							</div>
						</div>
					</li>
                                        
					<li class="nav-item dropdown">
						<a class="nav-link text-left text-dark" style="font-size:1em;" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user }}<i class="fas fa-angle-down"></i> </i></a>
						<div class="dropdown-menu dropdown-menu-right">
							<a class="dropdown-item" href="/utilizadores/UserDetail/{{request.user.id}}">Gerir conta</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'Users:logout' %}">Terminar sessão</a>
						</div>
					</li>
				</ul>
			</div>
		</nav>
			{% block content %}
			{% endblock %}
	</div>
    {% include "main/modal.html" %}
</body>
{% include "main/scripts.html" %}
{% endblock %}

templates/main/search_form.html
<h2>Geral</h2>
<div class="input-group mb-3">
    <input class="form-control" name="name" type="text" placeholder="name...">
    <input class="form-control" name="date_initial" type="date" placeholder="...">
    <input class="form-control" name="date_final" type="date" placeholder="...">
</div>
<h2>Frases</h2>
<div class="input-group mb-3">
    <input class="form-control" name="frase_verbo" type="text" placeholder="Verbos">
    <input class="form-control" name="frase_sujeito" type="text" placeholder="Sujeito">
    <input class="form-control" name="frase_receptor" type="text" placeholder="Receptor">
</div>
<h2>Verbos</h2>
<div class="input-group mb-3">
    <input class="form-control" name="verbo_tipo" type="text" placeholder="Tipo">
</div>
<h2>Agrupamentos</h2>
<div class="input-group mb-3">
    <input class="form-control" name="group_frases" type="text" placeholder="Frases">
</div>
<h2>Padroes</h2>
<div class="input-group mb-3">
    <input class="form-control" name="pattern_groups" type="text" placeholder="Agrupamentos">
</div>

templates/main/search_results.html
{% extends "main/navbar.html" %}
{% block content %}


<div class="container">


  <!--{% if perms.Users.add_user %}
      {% include "tables/user.html" with object_list=users %}
      {% endif %}-->
  {% if perms.Activities.add_sentence %}
  {% include "tables/sentence.html" with object_list=sentences %}
  {% endif %}
  {% if perms.Activities.add_group %}
  {% include "tables/group.html" with object_list=groups %}
  {% endif %}
  {% if perms.Activities.add_pattern %}
  {% include "tables/pattern.html" with object_list=patterns %}
  {% endif %}
  {% if perms.Activities.add_verb %}
  {% include "tables/verb.html" with object_list=verbs %}
  {% endif %}

  <!--{% if perms.Processes.add_process %}
      {% include "tables/process.html" with object_list=processes %}
      {% endif %}
      {% if perms.Processes.add_activity %}
      {% include "tables/activity.html" with object_list=activities %}
      {% endif %}-->
</div>
{% endblock %}