Activities/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #==========   VERB   ==========#
    path('verbs/', views.ListVerb.as_view(), name='verb_list'),
    path('verb/<int:pk>', views.DetailVerb.as_view(), name='verb_detail'),
    path('create_verb/', views.CreateVerb.as_view(), name='verb_create'),
    path('update_verb<int:pk>/',
         views.UpdateVerb.as_view(),
         name='verb_update'),
    path('delete_verb<int:pk>/',
         views.DeleteVerb.as_view(),
         name='verb_delete'),
    #==========   VERB   ==========#
    
    
    
    #==========   SENTENCE   ==========#
    path('sentences/', views.ListSentence.as_view(), name='sentence_list'),
    path('sentence/<int:pk>', views.DetailSentence.as_view(),
         name='sentence_detail'),
    path('create_sentence/', views.CreateSentence.as_view(),
         name='sentence_create'),
    path('update_sentence<int:pk>/',
         views.UpdateSentence.as_view(),
         name='sentence_update'),
    path('delete_sentence<int:pk>/',
         views.DeleteSentence.as_view(),
         name='sentence_delete'),
    #==========   SENTENCE   ==========#
    
    
    
    #==========   GROUP   ==========#
    path('groups/', views.ListGroup.as_view(), name='group_list'),
    path('group/<int:pk>', views.DetailGroup.as_view(),
         name='group_detail'),
    path('create_group/', views.CreateGroup.as_view(),
         name='group_create'),
    path('update_group<int:pk>/',
         views.UpdateGroup.as_view(),
         name='group_update'),
    path('delete_group<int:pk>/',
         views.DeleteGroup.as_view(),
         name='group_delete'),
    #==========   GROUP   ==========#

    
    
    #==========   PATTERN   ==========#
    path('patterns/', views.ListPattern.as_view(), name='pattern_list'),
    path('pattern/<int:pk>', views.DetailPattern.as_view(),
         name='pattern_detail'),
    path('create_pattern/', views.CreatePattern.as_view(),
         name='pattern_create'),
    path('update_pattern<int:pk>/',
         views.UpdatePattern.as_view(),
         name='pattern_update'),
    path('delete_pattern<int:pk>/',
         views.DeletePattern.as_view(),
         name='pattern_delete'),
    #==========   PATTERN   ==========#
    
    
    
    #==========   RESOURCE   ==========#
    path('resources/', views.ListResource.as_view(), name='resource_list'),
    path('resource/<int:pk>', views.DetailResource.as_view(),
         name='resource_detail'),
    path('create_resource/', views.CreateResource.as_view(),
         name='resource_create'),
    path('update_resource/<int:pk>',
         views.UpdateResource.as_view(),
         name='resource_update'),
    path('delete_resource/<int:pk>',
         views.DeleteResource.as_view(),
         name='resource_delete'),
    #==========   RESOURCE   ==========#
    
    
    
    #==========   ARTEFACT   ==========#
    path('artefacts/', views.ListArtefact.as_view(), name='artefact_list'),
    path('artefact/<int:pk>', views.DetailArtefact.as_view(),
         name='artefact_detail'),
    path('create_artefact/', views.CreateArtefact.as_view(),
         name='artefact_create'),
    path('update_artefact/<int:pk>',
         views.UpdateArtefact.as_view(),
         name='artefact_update'),
    path('delete_artefact/<int:pk>',
         views.DeleteArtefact.as_view(),
         name='artefact_delete'),
    #==========   ARTEFACT   ==========#
]

Core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home, name='home'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search_results/', views.SearchResultsView.as_view(),
         name='search_results'),
]

Users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "Users"

urlpatterns = [
    path("utilizadores", views.utilizadores, name="utilizadores"),
    path("utilizadores/UserCreate", login_required(views.UserCreate.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserCreate"),
    path("utilizadores/UserDelete/<int:pk>", login_required(views.UserDelete.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserDelete"),
    path("utilizadores/UserUpdate/<int:pk>", login_required(views.UserUpdate.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserUpdate"),
    path("utilizadores/UserUpdateEmail/<int:pk>", login_required(views.UserUpdateEmail.as_view(success_url=('/')),login_url="/login"),  name="UserUpdateEmail"),
    path("utilizadores/UserChangePassword/<int:pk>", login_required(views.UserChangePassword.as_view(success_url=('/')),login_url="/login"),  name="UserUpdatePassword"),
    path("utilizadores/UserDetail/<int:pk>", login_required(views.UserDetail.as_view(),login_url="/login"), name="UserDetail"  ),
    path("empresas", views.empresas, name="empresas"),
    path("empresas/OrganizationCreate", login_required(views.OrganizationCreate.as_view(success_url=('/empresas')), login_url="/login"), name="empresas"),
    path("empresas/OrganizationDelete/<int:pk>", login_required(views.OrganizationDelete.as_view(success_url=('/empresas')),login_url="/login"),  name="OrganizationDelete"),
    path("empresas/OrganizationUpdate/<int:pk>", login_required(views.OrganizationUpdate.as_view(success_url=('/empresas')),login_url="/login"),  name="OrganizationUpdate"),
    path("empresas/OrganizationDetail/<int:pk>", login_required(views.OrganizationDetail.as_view(),login_url="/login"), name="OrganizationDetail"  ),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
]

processes/urls.py
from django.urls import path
from . import views 
from django.contrib.auth.decorators import login_required

app_name = "processes"

urlpatterns = [
    path("processos", views.processos, name="processos"),
    path("processos/ProcessCreate", login_required(views.ProcessCreate.as_view(success_url=('/processos')),login_url="/login"), name="ProcessCreate"),
    path("processos/ProcessUpdate/<int:pk>", login_required(views.ProcessUpdate.as_view(success_url=('/processos')),login_url="/login"), name="ProcessUpdate"),
    path("processos/ProcessDelete/<int:pk>", login_required(views.ProcessDelete.as_view(success_url=('/processos')),login_url="/login"), name="ProcessDelete"),
    path("processos/ProcessDetail/<int:pk>", login_required(views.ProcessDetail.as_view(),login_url="/login"), name="ProcessDetail"),
    path("actividades", views.actividades, name="actividades"),
    path("actividades/ActivityCreate", login_required(views.ActivityCreate.as_view(success_url=('/actividades')),login_url="/login"), name="ActivityCreate"),
    path("actividades/ActivityDetail/<int:pk>", login_required(views.ActivityDetail.as_view(), login_url="/login"), name="ActivityDetail"),
    path("actividades/ActivityUpdate/<int:pk>", login_required(views.ActivityUpdate.as_view(success_url=('/actividades')),login_url="/login") , name="ActivityUpdate"),
    path("actividades/ActivityDelete/<int:pk>", login_required(views.ActivityDelete.as_view(success_url=('/actividades')),login_url="/login"), name="ActivityDelete"),
    path("actividades/ActivitySwap/<int:pk>/<int:fk>", login_required(views.ActivitySwap.as_view(success_url=('/actividades/AssociateReferer')),login_url="/login"), name="ActivitySwap"),
    path("actividades/AssociateReferer", views.AssociateReferer, name="AssociateReferer"),
    path("actividades/ActivityDessociate/<int:pk>", views.removeActivityFromProcess, name="ActivityDessociate"),
    path("actividades/PatternDessociate/<int:pk>/<int:fk>", views.removePatternFromActivity, name="PatternDessociate"),
    path("actividades/PatternAssociate/<int:pk>/<int:fk>", views.addPatternToActivity, name="PatternAssociate"),
    path("produtos", views.produtos, name="produtos"),
    path("produtos/ProductCreate", login_required(views.ProductCreate.as_view(success_url=('/produtos')),login_url="/login"), name="ProductCreate"),
    path("produtos/ProductDetail/<int:pk>", login_required(views.ProductDetail.as_view(),login_url="/login"), name="ProductDetail"),
    path("produtos/ProductUpdate/<int:pk>", login_required(views.ProductUpdate.as_view(success_url=('/produtos')),login_url="/login"), name="ProductUpdate"),
    path("produtos/ProductDelete/<int:pk>", login_required(views.ProductDelete.as_view(success_url=('/produtos')),login_url="/login"), name="ProductDelete"),
    path("produtos/ProductDessociate/<int:pk>/<int:fk>", views.removeActivityFromProduct, name="ProductDessociate"),
    path("produtos/ProductAssociate/<int:pk>/<int:fk>", views.addActivityToProduct, name="ProductAssociate"),
    path("papeis", views.papeis, name="papeis"),
    path("papeis/RoleCreate", login_required(views.RoleCreate.as_view(success_url=('/papeis')),login_url="/login"), name="RoleCreate"),
    path("papeis/RoleDetail/<int:pk>", login_required(views.RoleDetail.as_view(),login_url="/login"), name="RoleDetail"),
    path("papeis/RoleUpdate/<int:pk>", login_required(views.RoleUpdate.as_view(success_url=('/papeis')),login_url="/login"), name="RoleUpdate"),
    path("papeis/RoleDelete/<int:pk>", login_required(views.RoleDelete.as_view(success_url=('/papeis')),login_url="/login"), name="RoleDelete"),
    path("actividades/RoleDessociate/<int:pk>/<int:fk>", views.removeRoleFromActivity, name="RoleDessociate"),
    path("actividades/RoleAssociate/<int:pk>/<int:fk>", views.addRoleToActivity, name="RoleAssociate"),
    path('actividades/SeeProcess/<int:pk>/', views.ViewProcess.as_view(), name='ViewProcess'),
    path('actividades/SeePattern/<int:pk>/', views.ViewPattern.as_view(), name='ViewPattern'),
    path('actividades/SeeProduct/<int:pk>/', views.ViewProduct.as_view(), name='ViewProduct'),
    path('actividades/SeeRole/<int:pk>/', views.ViewRole.as_view(), name='ViewRole'),
    path('actividades/SeeActivity/<int:pk>/', views.ViewActivity.as_view(), name='ViewActivity'),
]

Users/models.py
import django
from django.db import models
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import AbstractUser, Group

# Create your models here.
class Organization(models.Model):
    name = models.CharField(max_length=200, unique=True, blank=False)
    location = models.CharField(max_length=200, blank=False)
    def __str__(self):
        return self.name



class User(AbstractUser):
    id = models.AutoField(db_column='ID',primary_key=True)
    username = models.CharField(db_column='UserName',
                                max_length=255,
                                unique=True)
    useremail = models.CharField(db_column='UserEmail',
                                 max_length=255)
    password = models.CharField(db_column='Password',
                                max_length=255,
                                blank=True, null=True)

    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)




    class Meta:
        managed = True
        db_table = 'User'
        permissions = (
            ("test_GProc", "Teste de permissao geral Gestor de Processos"),
            ("test_Analist", "Teste de permissao geral Analista"),
            ("test_Func", "Teste de permissao geral Funcionário"),
            ("test_Admin", "Teste de permissao geral Administrador"),)

processes/models.py
import django
from django.db import models
from django.core import validators
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import AbstractUser, Group
from Users.models import User, Organization
from Activities.models import Pattern
from django.core.exceptions import ValidationError

# Create your models here.

class Process(models.Model):
    process_name = models.CharField(max_length=200)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    creation_date = models.DateTimeField("date created", default=django.utils.timezone.now)
    description = models.TextField(max_length=400)
    


    def __str__(self):
        return self.process_name

class Activity(models.Model):
    activity_name = models.CharField(max_length=200)
    process = models.ForeignKey(Process, null=True,blank=True, on_delete=models.SET_NULL)
    description = models.TextField(max_length=400)
    role = models.ManyToManyField('Role', blank=True)
    original = models.ForeignKey('self', blank=True, null=True,on_delete=models.SET_NULL)
    pattern = models.ManyToManyField('Activities.Pattern', blank=True)
    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)
    class Meta:
        verbose_name = ("Activity") 

    def __str__(self):
        return self.activity_name

    def clean(self):
        incident = Activity.objects.filter(activity_name=self.activity_name).exclude(process__isnull=False)
        if incident and self.original is None:
                if not Activity.objects.filter(id=self.pk).exists() : # check if any object exists
                    raise ValidationError('Já existe uma Actividade Base com este nome.')
                elif not incident[0].pk == self.pk: 
                    raise ValidationError('Já existe uma Actividade Base com este nome.')

class Role(models.Model):
    role_name = models.CharField(max_length=200)
    description = models.TextField(max_length=300)
    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.role_name



class Product(models.Model):
    product_name = models.CharField(max_length=200)
    product_format = models.CharField(max_length=200)
    activity = models.ManyToManyField(Activity, blank=True)
    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)
    product_input = models.CharField(max_length=200)
    product_output = models.CharField(max_length=200)
    def clean(self):
        incident = Product.objects.filter(organization__id=self.organization.id).filter(product_name=self.product_name)
        if incident:
            if not Product.objects.filter(id=self.pk).exists() : # check if any object exists
                raise ValidationError('Já existe um Produto com este nome.')
            elif not incident[0].pk == self.pk: 
                raise ValidationError('Já existe um Produto com este nome.')

    def __str__(self):
        return self.product_name

Activities/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import Sentence


class SentenceForm(forms.ModelForm):


    def clean(self):
        super(SentenceForm, self).clean()
        if bool(self.cleaned_data['verbid']) == bool(
                self.cleaned_data['verb_sug']):
            raise ValidationError("Please, fill the first or second field")

    class Meta:
        model = Sentence
        fields = ['sentencename', 'subject', 'verb_sug', 'verbid',
                  'receiver', 'resource_sug', 'resourceid',
                  'art_sug', 'artefactid', 'datarealizado']

Users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from tinymce.widgets import TinyMCE
from django.db import models
from .models import   User, Organization
from django.forms import ModelForm

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    group = forms.ModelChoiceField(queryset=Group.objects.all())
    organization = forms.ModelChoiceField(queryset=Organization.objects.all())
    class Meta:
        model = User
        fields = ("username", "email", "group", "organization", "password1", "password2",)
        

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        profile= self.cleaned_data.get('group')
        group = profile
        organization = self.cleaned_data['organization']
        if commit:
            user.save()
            user.groups.set(profile)
        return user

processes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from tinymce.widgets import TinyMCE
from django.db import models
from processes.models import Process, Activity, Role, Product
from Users.models import   User, Organization
from django.forms import ModelForm
from django.core.exceptions import ValidationError

class SwapActivityForm(ModelForm):
    activity_name = forms.CharField(required=True,max_length=200)
    process = forms.ModelMultipleChoiceField(queryset=Process.objects.all())
    description = forms.Textarea()
    role = forms.ModelMultipleChoiceField(queryset=Role.objects.all())

    class Meta:
        model = Activity
        fields = ("activity_name", "process", "description", "role",)

    def save(self, commit=True):
        activity = super(SwapActivityForm, self).save(commit=False)
        activity_name = self.cleaned_data['activity_name']
        grole= Role.objects.get(role_name=self.cleaned_data.get('role'))
     #   process = Process.objects.get(name=self.cleaned_data.get('process'))
        description = self.cleaned_data['description']
        if commit:
            activity.save()
            activity.role.add(grole)
        return activity        

templates/processes/forms/activity_confirm_delete.html
{% extends "main/navbar.html" %}
{% block content %}
{% if perms.Users.test_GProc or perms.Users.test_Analist  %} 
<div class="container">
        <form method="post">{% csrf_token %}
     

  <p>Tem a certeza que pretende eliminar a Actividade <b>"{{ object.activity_name}}</b>"?</p>          
  <a class ="text-danger mr-3"href="/actividades">Cancelar</a>
  <button type="submit" class="btn text-white">Eliminar</button>
  {% else %}
  <a class ="text-danger mr-3"href="/actividades">Cancelar</a>
  {% endif %}
</form>
</div>
{% endblock %}

templates/processes/forms/activity_detail.html
{% extends "main/navbar.html" %}
{% block content %}
{% if perms.Users.test_GProc or perms.Users.test_Analist %}
<div class="container">
        <h3>Actividade: {{object.activity_name}} </h3>
        <hr>
          <div class="row">
            <div class="col-sm-2"> Descrição: </div>
            <div class="col-sm-10">{{object.description}}</div>
        </div>
        {% if object.process != None %}
        <hr>
        <div class = "row">
          <div class = "col-sm-12"> Processo associado: <a href="/processos/ProcessDetail/{{object.process.id}}">{{object.process}}</a></div>
              </div>
              {% endif %}
      <hr>
      {% if perms.Users.test_GProc or object.process == None %}
        <p><a href="/actividades/ActivityUpdate/{{object.id}}"> <button type="button" class="btn text-white">Editar actividade</button></a></p>
        <br>
{% endif %}
        {% if patterns|length > 0 or non_patterns|length > 0 %}
<div class = "row">
  <div class = "col-sm-6"> <h3>Padrões associados à actividade:</h3></div>
  <div class = "col-sm-6"> <h3>Padrões não associados:</h3></div>
      </div>
        <hr>
        <div class ="row">
        <div class = "col-sm-6  colseparator" >
        {% for pat in patterns %}
        <div class="row">
        <div class="col-sm-5"><a href="#">{{pat}}</a></div>
        <div class="col-sm-7 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewPattern" pat.id %}", "Ver Padrão", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;&nbsp;</a>
        <a href="/actividades/PatternDessociate/{{object.id}}/{{pat.id  }}"><i class="material-icons text-danger">clear</i>&nbsp;</a></div>
        </div>
        {% endfor %}</div>
        <div class = "col-sm-6">
            {% for pat in non_patterns %}
            <div class="row">
            <div class="col-sm-5"><a href="#">{{pat}}</a></div>
            <div class="col-sm-7 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewPattern" pat.id %}", "Ver Padrão", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;&nbsp;</a>
            <a href="/actividades/PatternAssociate/{{object.id}}/{{pat.id}}"><i class="material-icons text-success">add</i>&nbsp;</a></div>
            </div>
            {% endfor %}</div></div>
        <hr>
        <br>

        {% endif %}

    {% if act_products|length > 0 or non_products|length > 0 %}
        <div class = "row">
            <div class = "col-sm-6"> <h3>Produtos associados à actividade:</h3></div>
            <div class = "col-sm-6"> <h3>Produtos não associados:</h3></div>
                </div>
        <hr>

        <div class ="row">
            <div class = "col-sm-6  colseparator" >
        {% for product in act_products %}
        <div class="row">
        <div class="col-sm-5"> <a href="/produtos/ProductDetail/{{product.id}}">{{product}}</a></div>
        <div class="col-sm-7 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewProduct" product.id %}", "Ver Produto", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;&nbsp;</a>
        <a href="/produtos/ProductDessociate/{{product.id}}/{{object.id}}"><i class="material-icons text-danger">clear</i>&nbsp;</a></div>
        </div>
        {% endfor %}</div>
        <div class = "col-sm-6" >
            {% for product in non_products %}
            <div class="row">
            <div class="col-sm-5"><a href="/produtos/ProductDetail/{{product.id}}">{{product}}</a></div>
            <div class="col-sm-7 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewProduct" product.id %}", "Ver Produto", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;&nbsp;</a>
            <a href="/produtos/ProductAssociate/{{product.id}}/{{object.id}}"><i class="material-icons text-success">add</i>&nbsp;</a></div>
            </div>
            {% endfor %}</div>
          
      </div>

        <hr>
        <br>
        {% endif %}
        {% if roles|length > 0 or non_roles|length > 0 %}
        <div class = "row">
            <div class = "col-sm-6"> <h3>Papéis associados à actividade:</h3></div>
            <div class = "col-sm-6"> <h3>Papéis não associados:</h3></div>
                </div>
        <hr>
        <div class ="row">
            <div class = "col-sm-6  colseparator" >
        {% for rol in roles %}
        <div class="row">
            <div class="col-sm-5"><a href="/papeis/RoleDetail/{{rol.id}}">{{rol}}</a></div>
            <div class="col-sm-7 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewRole" rol.id %}", "Ver Papel", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;</a>
                {% if perms.Users.test_GProc %} <a href="/actividades/RoleDessociate/{{object.id}}/{{rol.id}}"><i class="material-icons text-danger">clear</i>&nbsp;</a>{% endif %}</div>
        </div>
        {% endfor %}</div>
        <div class = "col-sm-6" >
            {% for rol in non_roles %}
            <div class="row">
            <div class="col-sm-5"><a href="/papeis/RoleDetail/{{rol.id}}">{{rol}}</a></div>
            <div class="col-sm-7 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewRole" rol.id %}", "Ver Papel", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;</a>
                {% if perms.Users.test_GProc %} <a href="/actividades/RoleAssociate/{{object.id}}/{{rol.id}}"><i class="material-icons text-success">add</i>&nbsp;</a>{% endif %}</div>
            </div>
            {% endfor %}</div>
      
      </div>
      <hr>
        <br>
        {% endif %}
        {% if object.process == None and procs|length > 0 %}
        <div class = "row">
          <div class = "col-sm-12"> <h3>Processos a associar:</h3></div>
              </div>
      <hr>

      {% for proc in procs %}
      <div class="row">
          <div class="col-sm-3"><a href="/processos/ProcessDetail/{{proc.id}}">{{proc}}</a></div>
          <div class="col-sm-3 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewProcess" proc.id %}", "Ver Processo", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;</a>
            {% if perms.Users.test_GProc %}  <a href="/actividades/ActivitySwap/{{object.id}}/{{proc.id}}"><i class="material-icons text-success">add</i>&nbsp;</a>{% endif %}</div>
      </div>
      {% endfor %}

      {% endif %}
    </div>


        

        <hr>
        <br>
        {% else %}
        <h2>Não tem permissão para visualizar esta página.</h2>
        {% endif %}
        {% endblock %}

templates/processes/forms/activity_form.html
{% extends "main/navbar.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% if perms.Users.test_GProc or perms.Users.test_Analist  %} 
<div class="container">
    
<form method="post">{% csrf_token %}
        {{ form|crispy }}
    <a href="/actividades" class="text-danger">Cancelar</a>
    <button type="submit" class="btn text-white">Guardar</button>

</form>

</div>
{% else %}
<h2>Não tem permissão para realizar esta ação.</h2>
{% endif %}
{% endblock %}

templates/processes/forms/organization_update_form.html
{% extends "main/navbar.html" %}
{% block content %}
{% load crispy_forms_tags %}

{% if perms.Users.test_Admin %}  
<div class="container">
    
<form method="post">{% csrf_token %}
        {{ form|crispy}}
    
        <a href="/empresas" class="text-danger">Cancelar</a>
        <button type="submit" class="btn text-white">Guardar</button>

</form>

</div>
{% else %}
<h2>Não tem permissão para realizar esta ação.</h2>
{% endif %}
{% endblock %}

templates/processes/forms/process_detail.html
{% extends "main/navbar.html" %}
{% block content %}
{% if perms.Users.test_GProc or perms.Users.test_Analist  %}
<div class="container">
        <h3>Processo: {{object.process_name}} </h3>
        <hr>
            <div class="row">
                <div class="col-sm-2">Criado por: </div> 
                <div class="col-sm-2"> {{object.user}}</div>
                </div>
                <hr>
         <div class="row">
                <div class="col-sm-2"> Data criação:</div>
                <div class="col-sm-3">{{object.creation_date}}</div>
            </div>
          <hr>
          <div class="row">
            <div class="col-sm-2"> Descrição:</div>
            <div class="col-sm-4">{{object.description}}</div>
        </div>
      <hr>
      {% if perms.Users.test_GProc %}
        <p><a href="/processos/ProcessUpdate/{{object.id}}"> <button type="button" class="btn text-white">Editar processo</button></a></p>
       {% endif %} <br>
        <h3>Actividades associadas ao Processo </h3>
        <hr>
        {% for act in proc_acts %}
        <div class="row">
        <div class="col-sm-4"><a href="/actividades/ActivityDetail/{{act.id}}">{{act}}</a></div>
        <div class="col-sm-7 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewActivity" act.id %}", "Ver Actividade", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;</a>
        {% if perms.Users.test_GProc %}
        <a href="/actividades/ActivityDessociate/{{act.id}}"><i class="material-icons text-danger">clear</i>&nbsp;</a>
        {% endif %}
        </div></div>
        {% endfor %}
        <hr>
        <br>
        <h3>Actividades base disponíveis: </h3>
        <hr>
        {% for act in non_acts %}
        <div class="row">
        <div class="col-sm-4"><a href="/actividades/ActivityDetail/{{act.id}}">{{act}}</a></div>
        <div class="col-sm-7 text-right"><a data-toggle="modal" onclick='newModal("{% url "processes:ViewActivity" act.id %}", "Ver Actividade", "#Viewmodal", "")' href=''><i class="material-icons">search</i>&nbsp;</a>
        {% if perms.Users.test_GProc %}
        <a href="/actividades/ActivitySwap/{{act.id}}/{{pid}}"><i class="material-icons text-success">add</i>&nbsp;</a>
        {% endif %}
        </div></div>
        {% endfor %}
        <hr>

        </div>
        {% else %}
        <h2>Não tem permissão para visualizar esta página.</h2>
        {% endif %}
        {% endblock %}